version: 2.1
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fd:30:c0:11:5a:d0:6e:4f:f6:03:0d:20:fd:e1:f6:f1"
      - checkout
      - deploy:
          command: |
            DAGS_PATH=testfolder/
            BRANCHES_REGEX=$(git branch -r | grep origin/ | sed -e 's/^  origin\//\\\.\//' | sed -e 's/ ->.*//' | sed -e 's/$/\$\\/' | tr '\n' '|' | sed -e 's/\\|$//')
            ssh $SSH_USER@$SSH_HOST \<< EOF
              mkdir -p /home/$SSH_USER/test
              cd /home/$SSH_USER/test
              find . -type d -not -regex $BRANCHES_REGEX -not -path . -print0 | xargs -0 -I {}/$CIRCLE_PROJECT_REPONAME rm -rf {}
            EOF
            for DAG in $DAGS_PATH*.py
            do
              sed -i '1s|^|import sys, pathlib\nsys.path.append(str(pathlib.Path(__file__).parent))\n|' $DAG
            done
            rsync -avuz $DAGS_PATH $SSH_USER@$SSH_HOST:~/test/$CIRCLE_BRANCH/$CIRCLE_PROJECT_REPONAME
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
                - /dev-.*/
