version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fd:30:c0:11:5a:d0:6e:4f:f6:03:0d:20:fd:e1:f6:f1"
      - run:
          name: The First Step
          command: |
            scp test.txt $SSH_USER@$SSH_HOST:~/test/
