version: 2.1
jobs:
  aws-ecr/build_and_push_image:
    account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
    repo: "${AWS_RESOURCE_NAME_PREFIX}"
    region: ${AWS_DEFAULT_REGION}
    tag: "${CIRCLE_SHA1}"
  aws-ecs/deploy-service-update:
    aws-region: ${AWS_DEFAULT_REGION}
    family: "${AWS_RESOURCE_NAME_PREFIX}-service"
    cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
    container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
