version: 2.1
jobs:
  deploy:
    docker:
      - image: buildpack-deps:bionic
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fd:30:c0:11:5a:d0:6e:4f:f6:03:0d:20:fd:e1:f6:f1"
      - run:
          name: disable StrictHostKeyChecking
          command: ssh -o "StrictHostKeyChecking=no" $SSH_USER@$SSH_HOST
      - checkout
      - deploy:
          command: |
            BRANCHES_REGEX=$(git branch -r | grep origin/ | sed -e 's/^  origin\//\\\.\//' | sed -e 's/ ->.*//' | sed -e 's/$/\$\\/' | tr '\n' '|' | sed -e 's/\\|$//')
            ssh $SSH_USER@$SSH_HOST \<< EOF
              mkdir -p /home/$SSH_USER/test
              cd /home/$SSH_USER/test
              find . -type d -not -regex $BRANCHES_REGEX -not -path . -print0 | xargs -0 -I {} rm -rf {}
            EOF
            if [ $CIRCLE_BRANCH = master ]
            then
              rsync -avuz testfolder/ $SSH_USER@$SSH_HOST:~/test/
            else
              rsync -avuz testfolder/ $SSH_USER@$SSH_HOST:~/test/$CIRCLE_BRANCH/
            fi
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
                - /dev-.*/