version: 2.1
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fd:30:c0:11:5a:d0:6e:4f:f6:03:0d:20:fd:e1:f6:f1"
      - checkout
      - deploy:
          command: |
            ssh $SSH_USER@$SSH_HOST mkdir -p /home/$SSH_USER/test
            if [ $CIRCLE_BRANCH = master ]
            then
              rsync -avuz testfolder $SSH_USER@$SSH_HOST:~/test/
            else
              rsync -avuz testfolder $SSH_USER@$SSH_HOST:~/test/$CIRCLE_BRANCH/
            fi
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
                - /dev-.*/